import { Sneaker } from '../../app/models/sneaker.model';

/**
 * Represents an array of sneakers.
 */
export const Sneakers: Sneaker[] = [
  {
    id: 1,
    name: 'Air Jordan 3 Retro Palomino',
    brand: 'Jordan',
    price: 165,
    image: 'AirJordan3.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 2,
    name: 'Air Jordan 4 Retro SB Green',
    brand: 'Jordan',
    price: 350,
    image: 'AirJordan4.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 3,
    name: 'Nike Air Force 1 High Green',
    brand: 'Nike',
    price: 135,
    image: 'dunkHigh.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 4,
    name: 'DUNK LOW MEDIUM CURRY',
    brand: 'Nike',
    price: 145,
    image: 'dunkLow.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 5,
    name: 'NB530 Green & Brown',
    brand: 'New Balance',
    price: 110,
    image: 'NB530.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 6,
    name: 'NB550 White Mint Green',
    brand: 'New Balance',
    price: 130,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 7,
    name: 'NB990v5 Grey',
    brand: 'New Balance',
    price: 175,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 8,
    name: 'NB992 Grey',
    brand: 'New Balance',
    price: 175,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 9,
    name: 'NB992 Black',
    brand: 'New Balance',
    price: 175,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 10,
    name: 'NB992 White',
    brand: 'New Balance',
    price: 175,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 11,
    name: 'DUNK LOW MEDIUM OLIVE',
    brand: 'Nike',
    price: 145,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 12,
    name: 'DUNK LOW COAST',
    brand: 'Nike',
    price: 145,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 13,
    name: 'DUNK LOW BLACK',
    brand: 'Nike',
    price: 145,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 14,
    name: 'DUNK LOW WHITE',
    brand: 'Nike',
    price: 145,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 15,
    name: 'DUNK LOW RED',
    brand: 'Nike',
    price: 145,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },
  {
    id: 16,
    name: 'DUNK LOW BLUE',
    brand: 'Nike',
    price: 145,
    image: 'NB550.png',
    description: 'Les Jordan 1 : emblématiques, cuir de qualité, style rétro, confort optimal, incontournables du streetwear.',
  },

  // more sneakers...
];
